import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1736942896946 implements MigrationInterface {
    name = 'Migrations1736942896946'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_3c1e58945b13642f502cc720a3\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_7640986091f782c4fa48e90584\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_be808a4abf6a43106453ee9b19\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`idx_variant_dimensions\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`idx_variant_media\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`idx_variant_type\` ON \`media_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_219645188a391081a10cd4004c\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`IDX_bc4a3a0ac419c3df8d3342c3ea\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`IDX_fdf9bc67d972734c85bb4f4837\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`idx_folder_name\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`idx_folder_parent\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`idx_folder_sort\` ON \`media_folders\``);
        await queryRunner.query(`DROP INDEX \`IDX_ad03a2107269bcec2331b7f885\` ON \`addresses\``);
        await queryRunner.query(`DROP INDEX \`IDX_04b3548499bb504689176c8849\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_128d39388b2d6cbeb68585d520\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ccd871bc19d6ec5dcc93cc5bb\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_36c7f5a6a8d1c7c23470457dc3\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_4542dd2f38a61354a040ba9fd5\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_610102b60fea1455310ccd299d\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_7d8bee0204106019488c4c50ff\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_7ecbd2d25cb0d431286e5604d7\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_8545816ff7233dc0aed923273f\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_90781acb0a5b9b32658b656c41\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_98c0562c3afc78514a32f56045\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_fd99bb073033ec13353c5f62c5\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe1a329950fe79a07fee9b8bfc\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_6fccf5ec03c172d27a28a82928\` ON \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c6da413723d6723776da6735c\` ON \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_b85f9ac24bf779f1fcd9331927\` ON \`cart_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_08a66913458db3e557f89c6e82\` ON \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_b5f695a59f5ebb50af3c816081\` ON \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_c19f7859d0ead8c988590e9f61\` ON \`carts\``);
        await queryRunner.query(`DROP INDEX \`IDX_6a72c3c0f683f6462415e653c3\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_831a5a06f879fb0bebf8965871\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac27b070934c64650ab339f4c6\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c24c4e5b35172410336a1e2a5\` ON \`deduction_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e8237158263c1dd0df284aad3\` ON \`deduction_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_616bbd7e219af9954647d1958c\` ON \`deduction_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_25a6f4ab4e3c2ce36d72866ef2\` ON \`salary_deductions\``);
        await queryRunner.query(`DROP INDEX \`IDX_9387f4c505caeb666373ebd0dc\` ON \`salary_deductions\``);
        await queryRunner.query(`DROP INDEX \`IDX_ec4f08aa628d4ac2b98615fad4\` ON \`salary_deductions\``);
        await queryRunner.query(`DROP INDEX \`IDX_0f5cbe00928ba4489cc7312573\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_204e9b624861ff4a5b26819210\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_a3ffb1c0c8416b9fc6f907b743\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_4cd42e472ee1226e2124d20f69\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`REL_c9ceb2ea9a5df49b0d830fa765\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_08bfd68df9aaed7d72469401a7\` ON \`payment_methods\``);
        await queryRunner.query(`DROP INDEX \`IDX_34f9b8c6dfb4ac3559f7e2820d\` ON \`payment_methods\``);
        await queryRunner.query(`DROP INDEX \`IDX_d7ca377fb1b828f45410bb269b\` ON \`payment_methods\``);
        await queryRunner.query(`DROP INDEX \`IDX_0809f43dd87efb042da320216f\` ON \`payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_3cbf41030b760b217db8dfae1e\` ON \`payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_d32b3c6b0d2c1d22604cbcc8c4\` ON \`payment_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_005269d8574e6fac0493715c30\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a05306052b5c834bf253bd63a\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_c361c0c645c9bd8d4875aa042a\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`idx_order_item_created\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`idx_order_item_order\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`idx_order_item_product\` ON \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f4b9818a08b822a31493fdee9\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_710e2d4957aa5878dfe94e4ac2\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_d42e0dcd4954bbebd2232624bd\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_order_created_at\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_order_payment_status\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_order_status_created\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`idx_order_user\` ON \`orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_57b88b98968b2728f5ea1fb474\` ON \`sellers\``);
        await queryRunner.query(`DROP INDEX \`IDX_97337ccbf692c58e6c7682de8a\` ON \`sellers\``);
        await queryRunner.query(`DROP INDEX \`IDX_c6fc7ec7d28e6493560fa9f587\` ON \`sellers\``);
        await queryRunner.query(`DROP INDEX \`IDX_4155d7846db53ac2c1d2903ba8\` ON \`review_metrics\``);
        await queryRunner.query(`DROP INDEX \`IDX_73c64233ea557a860ce10ab4ef\` ON \`review_metrics\``);
        await queryRunner.query(`DROP INDEX \`IDX_884e16e2905c1320f5e614ee6c\` ON \`review_metrics\``);
        await queryRunner.query(`DROP INDEX \`IDX_1df3d408b691e274fcc5f11cc1\` ON \`review_replies\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba79cc5b487adc14fc3fe8b484\` ON \`review_replies\``);
        await queryRunner.query(`DROP INDEX \`IDX_e65a6edf9bdb763ae60a7083ed\` ON \`review_replies\``);
        await queryRunner.query(`DROP INDEX \`IDX_231ae565c273ee700b283f15c1\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_4952a5c91db543e1bf2b91a3eb\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_9db5e0928b45dddc1b3ce6f2bf\` ON \`reviews\``);
        await queryRunner.query(`DROP INDEX \`IDX_12ab873251814ad54ddb41d45e\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_24dbc6126a28ff948da33e97d3\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_43bf08375ae7bfae7d55bc3a0c\` ON \`categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_0806c755e0aca124e67c0cf6d7\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_51287e43b0bd3e113a1ead339c\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_63fcb3d8806a6efd53dbc67430\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_active\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_category\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_discount\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_price_range\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_seller\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`idx_product_stock\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_c58bf8951c9a6ba9277eebcbf5\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`IDX_daa153fd17bdbf51724f4cd3e5\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`IDX_f4e0fcac36e050de337b670d8b\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`idx_media_active\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`idx_media_entity\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`idx_media_folder\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`idx_media_type_purpose\` ON \`media\``);
        await queryRunner.query(`DROP INDEX \`IDX_3af3a5d80e2d046e95031f39a0\` ON \`payroll_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_4242f0131e11ba54db34d0d7d3\` ON \`payroll_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_d15043ecb9af6aa22172f6ba9f\` ON \`payroll_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_a0365502b055164bc8234ae6ff\` ON \`companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_d4bc3e82a314fa9e29f652c2c2\` ON \`companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_df4b0a28099d9da123850b2d29\` ON \`companies\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`filename\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`height\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`quality\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`variantType\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`width\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deliveryPersonnelId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`otpCode\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`otpExpires\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`sellerId\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`deliveryStatus\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`discountAmount\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`discountPercentage\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`isDeleted\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`markedPrice\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sellingPrice\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`url\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`fileSize\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`dimensions\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`price\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`size\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`size\` enum ('THUMBNAIL', 'SMALL', 'MEDIUM', 'LARGE', 'ORIGINAL') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('ADMIN', 'EMPLOYEE', 'SELLER') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`sellers\` CHANGE \`tax_id\` \`tax_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sellers\` CHANGE \`isVerified\` \`isVerified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD CONSTRAINT \`FK_c93fce88e484793efb4ad22f03d\` FOREIGN KEY (\`mediaId\`) REFERENCES \`media\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP FOREIGN KEY \`FK_c93fce88e484793efb4ad22f03d\``);
        await queryRunner.query(`ALTER TABLE \`sellers\` CHANGE \`isVerified\` \`isVerified\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`sellers\` CHANGE \`tax_id\` \`tax_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`role\` \`role\` enum ('ADMIN', 'EMPLOYEE', 'SELLER', 'DELIVERY_PERSONNEL') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`size\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`size\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`price\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`dimensions\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`fileSize\``);
        await queryRunner.query(`ALTER TABLE \`media_variants\` DROP COLUMN \`url\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sellingPrice\` decimal NOT NULL COMMENT 'Final selling price after discount'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`markedPrice\` decimal NOT NULL COMMENT 'Original/Market price of the product'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`isDeleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`discountPercentage\` decimal(5,2) NOT NULL COMMENT 'Discount percentage' DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`discountAmount\` decimal NOT NULL COMMENT 'Discount amount' DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`deliveryStatus\` enum ('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`sellerId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`otpExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`otpCode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deliveryPersonnelId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`width\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`variantType\` enum ('thumb', 'sm', 'md', 'lg', 'original') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`quality\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`height\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`media_variants\` ADD \`filename\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_df4b0a28099d9da123850b2d29\` ON \`companies\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d4bc3e82a314fa9e29f652c2c2\` ON \`companies\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a0365502b055164bc8234ae6ff\` ON \`companies\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d15043ecb9af6aa22172f6ba9f\` ON \`payroll_settings\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4242f0131e11ba54db34d0d7d3\` ON \`payroll_settings\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3af3a5d80e2d046e95031f39a0\` ON \`payroll_settings\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_media_type_purpose\` ON \`media\` (\`type\`, \`purpose\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_media_folder\` ON \`media\` (\`folderId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_media_entity\` ON \`media\` (\`entityId\`, \`entityType\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_media_active\` ON \`media\` (\`isActive\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_f4e0fcac36e050de337b670d8b\` ON \`media\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_daa153fd17bdbf51724f4cd3e5\` ON \`media\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c58bf8951c9a6ba9277eebcbf5\` ON \`media\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_stock\` ON \`products\` (\`stock\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_seller\` ON \`products\` (\`sellerId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_price_range\` ON \`products\` (\`sellingPrice\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_discount\` ON \`products\` (\`discountPercentage\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_category\` ON \`products\` (\`categoryId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_product_active\` ON \`products\` (\`isActive\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_63fcb3d8806a6efd53dbc67430\` ON \`products\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_51287e43b0bd3e113a1ead339c\` ON \`products\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0806c755e0aca124e67c0cf6d7\` ON \`products\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_43bf08375ae7bfae7d55bc3a0c\` ON \`categories\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_24dbc6126a28ff948da33e97d3\` ON \`categories\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_12ab873251814ad54ddb41d45e\` ON \`categories\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9db5e0928b45dddc1b3ce6f2bf\` ON \`reviews\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4952a5c91db543e1bf2b91a3eb\` ON \`reviews\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_231ae565c273ee700b283f15c1\` ON \`reviews\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e65a6edf9bdb763ae60a7083ed\` ON \`review_replies\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ba79cc5b487adc14fc3fe8b484\` ON \`review_replies\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1df3d408b691e274fcc5f11cc1\` ON \`review_replies\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_884e16e2905c1320f5e614ee6c\` ON \`review_metrics\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_73c64233ea557a860ce10ab4ef\` ON \`review_metrics\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4155d7846db53ac2c1d2903ba8\` ON \`review_metrics\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c6fc7ec7d28e6493560fa9f587\` ON \`sellers\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_97337ccbf692c58e6c7682de8a\` ON \`sellers\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_57b88b98968b2728f5ea1fb474\` ON \`sellers\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_user\` ON \`orders\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_status_created\` ON \`orders\` (\`status\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_payment_status\` ON \`orders\` (\`paymentStatus\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_created_at\` ON \`orders\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d42e0dcd4954bbebd2232624bd\` ON \`orders\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_710e2d4957aa5878dfe94e4ac2\` ON \`orders\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1f4b9818a08b822a31493fdee9\` ON \`orders\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_item_product\` ON \`order_items\` (\`productId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_item_order\` ON \`order_items\` (\`orderId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_order_item_created\` ON \`order_items\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c361c0c645c9bd8d4875aa042a\` ON \`order_items\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9a05306052b5c834bf253bd63a\` ON \`order_items\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_005269d8574e6fac0493715c30\` ON \`order_items\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d32b3c6b0d2c1d22604cbcc8c4\` ON \`payment_transactions\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3cbf41030b760b217db8dfae1e\` ON \`payment_transactions\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0809f43dd87efb042da320216f\` ON \`payment_transactions\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d7ca377fb1b828f45410bb269b\` ON \`payment_methods\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_34f9b8c6dfb4ac3559f7e2820d\` ON \`payment_methods\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_08bfd68df9aaed7d72469401a7\` ON \`payment_methods\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_c9ceb2ea9a5df49b0d830fa765\` ON \`users\` (\`sellerId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_4cd42e472ee1226e2124d20f69\` ON \`users\` (\`deliveryPersonnelId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a3ffb1c0c8416b9fc6f907b743\` ON \`users\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_204e9b624861ff4a5b26819210\` ON \`users\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0f5cbe00928ba4489cc7312573\` ON \`users\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ec4f08aa628d4ac2b98615fad4\` ON \`salary_deductions\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9387f4c505caeb666373ebd0dc\` ON \`salary_deductions\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_25a6f4ab4e3c2ce36d72866ef2\` ON \`salary_deductions\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_616bbd7e219af9954647d1958c\` ON \`deduction_schedules\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3e8237158263c1dd0df284aad3\` ON \`deduction_schedules\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3c24c4e5b35172410336a1e2a5\` ON \`deduction_schedules\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ac27b070934c64650ab339f4c6\` ON \`notifications\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_831a5a06f879fb0bebf8965871\` ON \`notifications\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_6a72c3c0f683f6462415e653c3\` ON \`notifications\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c19f7859d0ead8c988590e9f61\` ON \`carts\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b5f695a59f5ebb50af3c816081\` ON \`carts\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_08a66913458db3e557f89c6e82\` ON \`carts\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b85f9ac24bf779f1fcd9331927\` ON \`cart_items\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8c6da413723d6723776da6735c\` ON \`cart_items\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_6fccf5ec03c172d27a28a82928\` ON \`cart_items\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fe1a329950fe79a07fee9b8bfc\` ON \`refresh_tokens\` (\`expires\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fd99bb073033ec13353c5f62c5\` ON \`refresh_tokens\` (\`userId\`, \`revoked\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_98c0562c3afc78514a32f56045\` ON \`refresh_tokens\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_90781acb0a5b9b32658b656c41\` ON \`refresh_tokens\` (\`userAgent\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8545816ff7233dc0aed923273f\` ON \`refresh_tokens\` (\`userId\`, \`expires\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7ecbd2d25cb0d431286e5604d7\` ON \`refresh_tokens\` (\`replacedByToken\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7d8bee0204106019488c4c50ff\` ON \`refresh_tokens\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_610102b60fea1455310ccd299d\` ON \`refresh_tokens\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_4542dd2f38a61354a040ba9fd5\` ON \`refresh_tokens\` (\`token\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_36c7f5a6a8d1c7c23470457dc3\` ON \`refresh_tokens\` (\`revoked\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_2ccd871bc19d6ec5dcc93cc5bb\` ON \`refresh_tokens\` (\`revokedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_128d39388b2d6cbeb68585d520\` ON \`refresh_tokens\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_04b3548499bb504689176c8849\` ON \`refresh_tokens\` (\`ipAddress\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ad03a2107269bcec2331b7f885\` ON \`addresses\` (\`userId\`, \`type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_folder_sort\` ON \`media_folders\` (\`sortOrder\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_folder_parent\` ON \`media_folders\` (\`parentId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_folder_name\` ON \`media_folders\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fdf9bc67d972734c85bb4f4837\` ON \`media_folders\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bc4a3a0ac419c3df8d3342c3ea\` ON \`media_folders\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_219645188a391081a10cd4004c\` ON \`media_folders\` (\`id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_variant_type\` ON \`media_variants\` (\`variantType\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_variant_media\` ON \`media_variants\` (\`mediaId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_variant_dimensions\` ON \`media_variants\` (\`width\`, \`height\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_be808a4abf6a43106453ee9b19\` ON \`media_variants\` (\`updatedAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7640986091f782c4fa48e90584\` ON \`media_variants\` (\`createdAt\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3c1e58945b13642f502cc720a3\` ON \`media_variants\` (\`id\`)`);
    }

}
